[package]
name = "rclone-manager"
version = "0.1.0"
description = "A simple GUI application for managing rclone remotes, mount options and configurations."
authors = ["Hakan İSMAİL"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "rclone_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2"
tokio = "1.44.1"
tauri-plugin-http = "2"
tauri-plugin-os = "2"
zip = "2.2.3"
reqwest = { version = "0.12.14", features = ["json", "blocking"] }
lazy_static = "1.5.0"
dirs = "6.0.0"
sysinfo = "0.33.1"
anyhow = "1.0.97"
tauri-plugin-store = "2"
tauri-plugin-notification = "2"
once_cell = "1.21.2"
log = "0.4.27"
env_logger = "0.11.7"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"

