# Rustfmt configuration for consistent Rust formatting
# See: https://rust-lang.github.io/rustfmt/
# Only stable options are included

max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
